name: 'lightdash_demo'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'lightdash_demo'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  lightdash_demo:
    # Config indicated by + and applies to all files under models/example/
    +materialized: table
    staging:
      +materialized: view
    marts:
      +materialized: table

seeds:
  lightdash_demo:
    +schema: raw_data
